# Generated by Django 3.2.6 on 2021-12-18 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diffuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FrontWing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RearWing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sidepod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Undertray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WheelFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WheelRear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SimulationMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('diffuser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.diffuser')),
                ('front_wing', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.frontwing')),
                ('nose', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.nose')),
                ('rear_wing', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.rearwing')),
                ('sidepod', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.sidepod')),
                ('simulation_meta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.simulationmeta')),
                ('suspension', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.suspension')),
                ('undertray', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.undertray')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
