# Generated by Django 3.2.6 on 2021-08-24 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('chassis_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('front_wing_name', models.CharField(max_length=10)),
                ('rear_wing_name', models.CharField(max_length=10)),
                ('sidepod_name', models.CharField(max_length=10)),
                ('diffuser_name', models.CharField(max_length=10)),
                ('undertray_name', models.CharField(max_length=10)),
                ('nose_name', models.CharField(max_length=10)),
                ('front_wing_df', models.IntegerField()),
                ('rear_wing_df', models.IntegerField()),
                ('sidepod_df', models.IntegerField()),
                ('diffuser_df', models.IntegerField()),
                ('undertray_df', models.IntegerField()),
                ('nose_df', models.IntegerField()),
                ('front_wing_drag', models.IntegerField()),
                ('rear_wing_drag', models.IntegerField()),
                ('sidepod_drag', models.IntegerField()),
                ('diffuser_drag', models.IntegerField()),
                ('undertray_drag', models.IntegerField()),
                ('nose_drag', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['chassis_name'],
            },
        ),
    ]
