# Generated by Django 3.2.6 on 2021-10-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastersheet', '0002_simulation_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='read',
        ),
    ]
