# Generated by Django 3.2.6 on 2021-11-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastersheet', '0003_remove_simulation_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='diffuser_df',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='diffuser_drag',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='front_wing_df',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='front_wing_drag',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='nose_df',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='nose_drag',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='rear_wing_df',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='rear_wing_drag',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='sidepod_df',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='sidepod_drag',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='undertray_df',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='undertray_drag',
            field=models.FloatField(),
        ),
    ]
