# Generated by Django 3.2.6 on 2021-11-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastersheet', '0004_auto_20211105_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='diffuser_df',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='diffuser_drag',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='front_wing_df',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='front_wing_drag',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='nose_df',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='nose_drag',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='rear_wing_df',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='rear_wing_drag',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='sidepod_df',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='sidepod_drag',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='undertray_df',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='undertray_drag',
            field=models.FloatField(blank=True),
        ),
    ]
