# Generated by Django 3.2.6 on 2021-11-26 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mastersheet', '0005_auto_20211119_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diffuser',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FrontWing',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nose',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RearWing',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sidepod',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Undertray',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WheelFront',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WheelRear',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('df', models.FloatField(blank=True)),
                ('drag', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='simulation',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='chassis_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='diffuser_df',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='diffuser_drag',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='diffuser_name',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='front_wing_df',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='front_wing_drag',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='front_wing_name',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='nose_df',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='nose_drag',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='nose_name',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='rear_wing_df',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='rear_wing_drag',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='rear_wing_name',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='sidepod_df',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='sidepod_drag',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='sidepod_name',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='undertray_df',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='undertray_drag',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='undertray_name',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='user',
        ),
        migrations.CreateModel(
            name='SimulationMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='simulation',
            name='diffuser',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.diffuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='front_wing',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.frontwing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='nose',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.nose'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='rear_wing',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.rearwing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='sidepod',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.sidepod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='undertray',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mastersheet.undertray'),
            preserve_default=False,
        ),
    ]
